CREATE TABLE IF NOT EXISTS accounts (
  code VARCHAR(20) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('asset', 'liability', 'equity', 'revenue', 'expense') NOT NULL,
  balance INT NOT NULL DEFAULT 0,
  has_sub BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS partners (
  code VARCHAR(20) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('customer', 'vendor', 'both') NOT NULL,
  account_code VARCHAR(20) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_partners_account_code (account_code)
);

CREATE TABLE IF NOT EXISTS journals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  debit VARCHAR(20) NOT NULL,
  debit_partner VARCHAR(20) NOT NULL DEFAULT '',
  credit VARCHAR(20) NOT NULL,
  credit_partner VARCHAR(20) NOT NULL DEFAULT '',
  amount INT NOT NULL,
  memo VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_journals_date (date),
  INDEX idx_journals_debit (debit),
  INDEX idx_journals_credit (credit)
);
